#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"

CRATE="dns_common" "${SCRIPT_DIR}/dot" "$@"
CRATE="dns_common_derive" "${SCRIPT_DIR}/dot" "$@"
CRATE="core" "${SCRIPT_DIR}/dot" "$@"
